### ISSUE TITLE
Add support DiscordSRV for general Townychat

### ISSUE THREAD

**Issue by Sprungente** [TownyAdvanced/TownyChat#21]
Adding support for DiscordSRV. For example for the generalchat. 

https://www.spigotmc.org/resources/discordsrv.18494/
https://github.com/DiscordSRV/DiscordSRV

**Comment by KarlOfDuty** [comment]
Towny chat already supports DiscordSRV, are you having any specific issues?

**Comment by Sprungente** [comment]
Yeah but i'm not sure if the issue on townyside. Messages between Server wont read on the other platform but messages in discord are readable in the console. Do you have any ideas?

**Comment by Sprungente** [comment]
i'm sure that the issue is townyside because without townychat everything does works.

**Comment by LlmDl** [comment]
We dont actually take TownyChat tickets on the townychat repo. File a ticket and fill out the form on the Towny repo.
